version: '3'
services:
  database:
    image: online-judge-database
    ports:
      - "5432:5432"
  api:
    image: online-judge-web
    command: ["api", "start"]
    ports:
      - "1337:1337"
    depends_on:
      - database
  judge:
    image: online-judge-web
    command: ["judge", "start"]
    ports:
      - "1338:1338"
    depends_on:
      - database
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin