version: '3.8'
services:
  database:
    image: online-judge-database
    ports:
      - "5432:5432"
  api:
    image: online-judge-web
    command: ["./scripts/wait-for-it.sh", "database:5432", "--", "online-judge", "api", "start"]
    ports:
      - "1337:1337"
    depends_on:
      - database
      - messaging
  judge:
    image: online-judge-web
    command: ["./scripts/wait-for-it.sh", "messaging:5672", "--", "online-judge", "judge", "start"]
    depends_on:
      - messaging
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5433:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
  messaging:
    image: online-judge-messaging
    ports:
      - "15672:15672"
      - "5672:5672"